---
common_sysctl_config:
  50jetbrains:
    comment: |-
      Increase the per-user inotify watch limit for JetBrains IDEs.
      https://youtrack.jetbrains.com/articles/IDEA-A-2/Inotify-Watches-Limit
    entries:
      - name: fs.inotify.max_user_watches
        value: 524288
