---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal
options:
  skip_ansible_check: true
  package_manager_path: /usr/bin/microdnf
dependencies:
  python_interpreter:
    package_system: python3
  ansible_core:
    package_pip: ansible-core
  galaxy: requirements.yml
  system:
    - openssh-clients
