---
collections:
  - name: ansible.posix
    version: 1.5.1
  - name: community.general
    version: 6.3.0
roles:
  - name: geerlingguy.docker
    version: 6.0.4
  - name: willshersystems.sshd
    version: v0.18.1
