---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 7.2.1
roles:
  - name: geerlingguy.docker
    version: 6.2.0
  - name: willshersystems.sshd
    version: v0.20.0
