---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 8.3.0
roles:
  - name: geerlingguy.docker
    version: 7.0.2
  - name: willshersystems.sshd
    version: v0.23.1
