---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 8.4.0
roles:
  - name: artis3n.tailscale
    version: v4.4.2
  - name: geerlingguy.docker
    version: 7.1.0
  - name: willshersystems.sshd
    version: v0.23.2
