---
collections:
  - name: ansible.posix
    version: 1.4.0
  - name: community.general
    version: 6.2.0
roles:
  - name: geerlingguy.docker
    version: 6.0.4
  - name: willshersystems.sshd
    version: v0.18.1
