---
collections:
  - name: ansible.posix
    version: 1.5.2
  - name: community.general
    version: 7.0.0
roles:
  - name: geerlingguy.docker
    version: 6.1.0
  - name: willshersystems.sshd
    version: v0.19.0
