---
- name: All hosts
  hosts: all
  roles:
    - common

- name: Gentoo hosts
  hosts: gentoo
  roles:
    - gentoo

- name: Ubuntu hosts
  hosts: ubuntu
  roles:
    - ubuntu
    - role: willshersystems.sshd
      become: true
    - role: geerlingguy.docker
      become: true
