---
- name: all
  hosts: all
  roles:
    - common

- name: gentoo
  hosts: gentoo
  roles:
    - gentoo

- name: ubuntu
  hosts: ubuntu
  roles:
    - ubuntu
    - role: geerlingguy.docker
      become: true
