---
- name: Set local service facts
  ansible.builtin.set_fact:
    gentoo_local_scripts: "{{ gentoo_local_scripts | default([]) + [item] }}"
  with_fileglob:
    - "{{ playbook_dir }}/host_templates/{{ inventory_hostname }}/etc/local.d/*.start.j2"
    - "{{ playbook_dir }}/host_templates/{{ inventory_hostname }}/etc/local.d/*.stop.j2"

- name: Set up local service
  when: gentoo_local_scripts
  become: true
  block:
    - name: Template local service scripts
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/etc/local.d/{{ item | basename | splitext | first }}"
        owner: root
        group: root
        mode: "0755"
      loop: "{{ gentoo_local_scripts }}"

    - name: Enable local service
      ansible.builtin.service:
        name: local
        enabled: true
