---
- name: Set up modprobe configuration
  when: modprobe_config
  become: yes
  block:
    - name: Template modprobe configuration
      ansible.builtin.template:
        src: etc/modprobe.d/template.conf.j2
        dest: "/etc/modprobe.d/{{ item.key }}.conf"
        owner: root
        group: root
        mode: "0644"
      loop: "{{ modprobe_config | dict2items }}"

    - name: Apply modprobe configuration
      community.general.modprobe: "{{ item.1 }}"
      loop: "{{ modprobe_config | subelements('modules') }}"
