---
- name: Set up sysctl configuration
  block:
    - name: Template sysctl configuration
      ansible.builtin.template:
        src: etc/sysctl.d/template.conf.j2
        dest: "/etc/sysctl.d/{{ item.key }}.conf"
        owner: root
        group: root
        mode: "0644"
      loop: "{{ sysctl_config | dict2items }}"

    - name: Apply sysctl configuration
      ansible.posix.sysctl: "{{ item.1 }}"
      loop: "{{ sysctl_config | subelements('entries') }}"
  when: sysctl_config
  become: yes
