---
- name: Set up sysctl configuration
  when: sysctl_config
  become: yes
  block:
    - name: Template sysctl configuration
      ansible.builtin.template:
        src: etc/sysctl.d/template.conf.j2
        dest: "/etc/sysctl.d/{{ item.key }}.conf"
        owner: root
        group: root
        mode: "0644"
      loop: "{{ sysctl_config | dict2items }}"

    - name: Apply sysctl configuration
      ansible.posix.sysctl:
        name: "{{ item.1.name }}"
        value: "{{ item.1.value }}"
        sysctl_file: "/etc/sysctl.d/{{ item.0.key }}.conf"
        sysctl_set: true
      loop: "{{ sysctl_config | dict2items | subelements('value.entries') }}"
