---
- name: Set up .profile.d
  ansible.builtin.blockinfile:
    path: .profile
    block: |
      for f in ~/.profile.d/*.sh; do
        [ -f "$f" ] && . "$f"
      done

- name: Set up .bashrc.d
  ansible.builtin.blockinfile:
    path: .bashrc
    block: |
      for f in ~/.bashrc.d/*.sh; do
        [ -f "$f" ] && . "$f"
      done

- name: Create directories
  ansible.builtin.file:
    path: '{{ item.path }}'
    mode: u=rwx,g=,o=
    state: directory
  with_community.general.filetree: templates/  # noqa deprecated-bare-vars
  when: item.state == 'directory'

- name: Template files
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.path }}'
    mode: u=rwX,g=,o=
  with_community.general.filetree: templates/  # noqa deprecated-bare-vars
  when: item.state == 'file'

- name: Set permissions
  ansible.builtin.file:
    dest: ./
    mode: u=rwX,g=,o=
    recurse: true

- name: Remove history
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - ".local/share/nano/search_history"
    - ".bash_history"
    - ".lesshst"
