---
- name: Set hostname
  ansible.builtin.import_tasks: hostname.yml
- name: Set up SSH configuration
  ansible.builtin.import_tasks: ssh.yml
- name: Set up sysctl configuration
  ansible.builtin.import_tasks: sysctl.yml
