---
- name: Set up SSH configuration
  when: authorized_keys
  become: yes
  block:
    - name: Set up users
      ansible.builtin.user:
        name: "{{ item }}"
      loop:
        "{{ authorized_keys.keys() }}"

    - name: Set up authorized keys
      ansible.posix.authorized_key:
        user: "{{ item.key }}"
        key: "{{ item.value }}"
        exclusive: yes
      loop:
        "{{ authorized_keys | dict2items }}"
