---
- name: Set up SSH configuration
  when: common_authorized_keys
  become: true
  block:
    - name: Set up users
      ansible.builtin.user:
        name: "{{ item }}"
      loop:
        "{{ common_authorized_keys.keys() }}"

    - name: Set up authorized keys
      ansible.posix.authorized_key:
        user: "{{ item.key }}"
        key: "{{ item.value }}"
        exclusive: true
      loop:
        "{{ common_authorized_keys | dict2items }}"
